version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 643426214971.dkr.ecr.ap-south-1.amazonaws.com
      - REPO_URI=643426214971.dkr.ecr.ap-south-1.amazonaws.com/flask-app
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Running tests...
      - pytest test_app.py

  build:
    commands:
      - echo Building Docker image...
      - docker build -t mywebapp:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker tag mywebapp:latest 643426214971.dkr.ecr.ap-south-1.amazonaws.com/codedeployrepo:latest
      - docker push 643426214971.dkr.ecr.ap-south-1.amazonaws.com/codedeployrepo:latest
      - echo Writing image definitions...
      - printf '[{"name":"flask-app","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
